version: 2.1
jobs:
  backend-build:
    docker:
      - image: circleci/ruby:2.5.3
      - image: circleci/postgres:11.8
    steps:
      - checkout
      - run: bundle -v
      - restore_cache:
        key: v1-medireco-backend-gem-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - run: bundle clean
      - save_cache:
        key: v1-medireco-backend-gem-{{ checksum "Gemfile.lock" }}
        paths:
          - ./vendor/bundle
      - run: bundle exec rails db:create db:schema:load
      - run: bundle exec rspec
