version: 2.1
orbs: 
  browser-tools: circleci/browser-tools@1.2
jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.2-node
        environment:
          BUNDLER_VERSION: 2.2.33
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - restore_cache:
          key: v1-medireco-backend-gem-{{ checksum "Gemfile.lock" }}
      - run:
          command: |
            gem install bundler -v $BUNDLER_VERSION
            bundle install --path vendor/bundle
            bundle clean
      - save_cache:
          key: v1-medireco-backend-gem-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rails db:create db:schema:load
      - browser-tools/install-chrome
      - run: bundle exec rspec
workflows:
  version: 2
  test:
    jobs: 
      - test
