version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          BUNDLER_VERSION: 2.2
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:11.8
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - restore_cache:
          key: v1-medireco-backend-gem-{{ checksum "Gemfile.lock" }}
      - run:
          command: |
            gem install bundler -v $BUNDLER_VERSION
            bundle install --path vendor/bundle
            bundle clean
      - save_cache:
          key: v1-medireco-backend-gem-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rails db:create db:schema:load
      - run: bundle exec rspec
  deploy-to-production:
    docker:
      - image: circleci/ruby:2.6.6
    steps:
      - checkout
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy-to-production:
          requires:
            - test
          filters:
            branches:
              only: master
